"""empty message

Revision ID: 10e3533fbe46
Revises: 3d16f16d947
Create Date: 2015-04-25 23:37:43.853993

"""

# revision identifiers, used by Alembic.
revision = '10e3533fbe46'
down_revision = '3d16f16d947'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_data')
    ### end Alembic commands ###
