"""empty message

Revision ID: 188f3b4e474a
Revises: fa403e7a2ad
Create Date: 2015-04-26 22:37:32.540733

"""

# revision identifiers, used by Alembic.
revision = '188f3b4e474a'
down_revision = 'fa403e7a2ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
