"""empty message

Revision ID: 265afd7a3ede
Revises: None
Create Date: 2015-05-02 21:41:47.668093

"""

# revision identifiers, used by Alembic.
revision = '265afd7a3ede'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
