"""empty message

Revision ID: 2ced87a67b02
Revises: 188f3b4e474a
Create Date: 2015-04-26 23:23:40.541660

"""

# revision identifiers, used by Alembic.
revision = '2ced87a67b02'
down_revision = '188f3b4e474a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kessel_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('operating_hours', sa.Integer(), nullable=True),
    sa.Column('pellets_stock', sa.Integer(), nullable=True),
    sa.Column('pellets_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lager_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('remaining_stock', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lager_data')
    op.drop_table('kessel_data')
    ### end Alembic commands ###
