"""empty message

Revision ID: 40cf3d21c6eb
Revises: 265afd7a3ede
Create Date: 2015-05-02 21:42:06.962720

"""

# revision identifiers, used by Alembic.
revision = '40cf3d21c6eb'
down_revision = '265afd7a3ede'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kessel_data', sa.Column('reservoir_capacity', sa.Integer(), nullable=True))
    op.add_column('kessel_data', sa.Column('usage_since_box_exhaustion', sa.Integer(), nullable=True))
    op.add_column('kessel_data', sa.Column('usage_since_deashing', sa.Integer(), nullable=True))
    op.add_column('kessel_data', sa.Column('usage_since_service', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kessel_data', 'usage_since_service')
    op.drop_column('kessel_data', 'usage_since_deashing')
    op.drop_column('kessel_data', 'usage_since_box_exhaustion')
    op.drop_column('kessel_data', 'reservoir_capacity')
    ### end Alembic commands ###
