"""empty message

Revision ID: 50798d201599
Revises: 477f8bf52d3
Create Date: 2015-12-19 00:14:22.342452

"""

# revision identifiers, used by Alembic.
revision = '50798d201599'
down_revision = '477f8bf52d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'kessel_data', sa.Column('status', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'kessel_data', 'status')
    ### end Alembic commands ###
