"""empty message

Revision ID: fa403e7a2ad
Revises: 10e3533fbe46
Create Date: 2015-04-26 22:36:21.768992

"""

# revision identifiers, used by Alembic.
revision = 'fa403e7a2ad'
down_revision = '10e3533fbe46'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
